# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i

      - name: run dev
        run: pnpm dev

      - name: Build site
        run: pnpm docs:build

      - name: Cd docs
        run: cd packages/ccui/docs/.vitepress/dist

      - name: git init
        run: git init

      - name: git add
        run: git add -A

      - name: git commit
        run: git commit -m 'deploy'

      - name: git push
        run: git push -f https://github.com/vaebe/ccui.git master:gh-pages
